# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LLC_cpp <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cpp`, X, L, A)
}

LLC_cpps <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cpps`, X, L, A)
}

LLC_cppl <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cppl`, X, L, A)
}

LLC_cppls <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cppls`, X, L, A)
}

