# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LLC_c <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_c`, X, L, A)
}

LLC_cs <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cs`, X, L, A)
}

LLC_cl <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cl`, X, L, A)
}

LLC_cls <- function(X, L, A) {
    .Call(`_CppLangComp_LLC_cls`, X, L, A)
}

